name: linting, testing, building
run-name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    # TODO: fix CI ui tests
    # ubuntu crash some ui tests
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install docker
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
      - name: install modules
        run: yarn
      - name: build production
        run: yarn build:production
        if: always()
      - name: linting typescript
        run: yarn lint:ts
        if: always()
      - name: linting scss
        run: yarn lint:scss
        if: always()
      - name: unit testing
        run: yarn test:unit
        if: always()
      - name: ui testing
        run: yarn test:ui
        if: always()