name: linting, testing, building
run-name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove lock
        run: rm -rf node_modules && rm -rf yarn.lock
      - name: Install node_modules
        run: yarn install
      - name: Build production
        run: yarn build:production
        if: always()
      - name: Linting typescript
        run: yarn lint:ts
        if: always()
      - name: Linting scss
        run: yarn lint:scss
        if: always()
      - name: Unit testing
        run: yarn test:unit
        if: always()
      - name: UI testing
        run: yarn test:ui
        if: always()
      # - name: deploy
      #   run: yarn deploy