name: linting, testing, building
run-name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    # TODO: fix CI ui tests
    # ubuntu crash some ui tests
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and start docker
        run: |
          brew install --cask docker
          open -a Docker.app

      - name: check docker daemon
        run: |
          # Make sure Docker Daemon is running
          if ! docker info; then
            echo "Restarting Docker..."
            osascript -e 'quit app "Docker"'
            sleep 5
            open -a Docker.app
            # Wait for Docker to be ready
            while ! docker info >/dev/null 2>&1; do sleep 1; done
          fi
      - name: install node_modules
        run: yarn
      - name: build production
        run: yarn build:production
        if: always()
      - name: linting typescript
        run: yarn lint:ts
        if: always()
      - name: linting scss
        run: yarn lint:scss
        if: always()
      - name: unit testing
        run: yarn test:unit
        if: always()
      - name: ui testing
        run: yarn test:ui
        if: always()