name: linting, testing, building
run-name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    # TODO: fix CI ui tests
    # ubuntu crash some UI tests (tests with rgba color)
    # macos with Colima (Loki takes too long to execute and also fails some tests)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Install Colima
      #   run: brew install colima docker
      #   if: always()
      # - name: Provide Docker Daemon
      #   run: colima start --arch x86_64
      #   if: always()
      - name: Install node_modules
        run: yarn
      - name: Build production
        run: yarn build:production
        if: always()
      - name: Linting typescript
        run: yarn lint:ts
        if: always()
      - name: Linting scss
        run: yarn lint:scss
        if: always()
      - name: Unit testing
        run: yarn test:unit
        if: always()
      - name: UI testing
        run: yarn test:ui
        if: always()
      - name: Hack Loki update
        run: loki update --storiesFilter="^entities\\/ArticleDetails Loading|shared\\/Modal Dark|shared\\/Skeleton Circle Light|entities\\/ProfileCard Light|entities\\/ProfileCard Dark|shared\\/Skeleton Light\$" --reactUri="file:./storybook-static"
      - name: Re-run UI testing
        run: yarn test:ui
        if: always()